config/routes.rb
Rails.application.routes.draw do
  
	root to: 'static_pages#home'

  devise_for :admins

#routes for visitors' website
  resources :articles, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :projects, only: [:index, :show]
  resources :contacts, only: [:new, :create]

#routes for admins' dashboard
  namespace :dashboard do

    resources :categories
    resources :contacts, only: [:index, :show]

    resources :admins, only: [:show, :edit, :update] do
      #for active_storage 
      resources :avatars
    end
    resources :events do
      # to define another update methode (dedicated to online / offline mode)
      member do    
        put :update_published
      end
    end

    resources :projects do
      #for active_storage 
      resources :pictures, only: [:create, :destroy]
      resources :thumbnails, only: [:create, :destroy]
      # to define another update methode (dedicated to online / offline mode)
      member do
        put :update_published
      end
    end

    resources :articles do
      #for active_storage 
      resources :images, only: [:create, :destroy]
      # to define another update methode (dedicated to online / offline mode)
      member do
        put :update_published
      end
    end
    
  end

end

app/models/project.rb
class Project < ApplicationRecord

  validates :title, presence: {message: "Merci d'indiquer le titre de la réalisation."}, length: {minimum: 2, message: "Le titre doit faire plus de 2 caractères."}
  validates :description, presence: {message: "Merci d'indiquer la description de la réalisation."}, length: {maximum: 200, message: "La description doit faire moins de 200 caractères maximum."}
  validates :content, presence: {message: "Merci d'indiquer le contenu de la réalisation."}

  belongs_to :admin
  has_many :project_categories
  has_many :categories, through: :project_categories
  has_one_attached :thumbnail
  has_many_attached :pictures

end

app/controllers/admin/projects_controller.rb
module Admin

	class ProjectsController < ApplicationController

		def index
	    @project = Project.all
	  end

	  def new
	    @project = Project.new
	  end

	  def create
	   @project = Project.create(project_params)
	  end

	  def show
	    @project = Project.find(params[:id])
	  end

	  def edit
	    @project = Project.find(params[:id])
	  end

	  def update
	    @project = Project.find(params[:id])
	    @project.update(project_params)
	  end

	  def destroy
	    @project = Project.find(params[:id])
	  end

	  private

	  def project_params
	    params.require(:project).permit(:title, :description, :content, :date, :published)
	  end

	end

end

app/controllers/dashboard/admins_controller.rb
module Dashboard

  class AdminsController < ApplicationController
    before_action :authenticate_admin!
    before_action :secret, only: [:show]

    def show
      @admin = Admin.find(params[:id])
    end

    def edit
      @admin = Admin.find(params[:id])
    end

    def update
      @admin = Admin.find(params[:id])
      if @admin.update(admin_params)
        redirect_to edit_dashboard_admin_path(@admin)
        flash[:notice] = "Modifications prises en compte!"
      else
        render "edit"
      end
    end

    private

    def admin_params
      params.require(:admin).permit(:first_name, :last_name, :pseudo, :description, :speciality, :display)
    end

    #method to prevent one admin to go on another admin's dashboard
    def secret
      @admin = Admin.find(params[:id])
      unless @admin.id == current_admin.id
        flash[:notice] = "Vous n'avez pas les droits d'accès au dashboard d'un autre admin!"
        redirect_to admin_path(current_admin)
      end
    end

  end

end

app/controllers/dashboard/application_controller.rb
module Dashboard

	class ApplicationController < ::ApplicationController
	end

end

app/controllers/dashboard/articles_controller.rb
module Dashboard

  class ArticlesController < ApplicationController
    before_action :authenticate_admin!
    before_action :secret, only: [:edit, :update, :destroy]

    def index
      @articles = Article.all.order('created_at DESC')
      @current_articles = Article.where(admin_id: current_admin.id)
    end

    def show
      @article = Article.find(params[:id])
    end

    def new
      @article = Article.new
    end

    def create
      @article = Article.new(article_params)
      @article.admin = current_admin
      if @article.save
        flash[:notice] = "Vous venez de créer un nouvel article. Ajoutez une photo et relisez les informations avant le mettre en ligne !"
        redirect_to edit_dashboard_article_path(@article)
      else
        render "new"
      end
    end

    def edit
      @article = Article.find(params[:id])
    end

    def update
      @article = Article.find(params[:id])
      if @article.update(article_params)
        flash[:notice] = "L'article '#{@article.title}' a bien été édité !"
        redirect_to dashboard_articles_path
      else
        render "edit"
      end
    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      respond_to do |format|
        format.html do
          flash[:notice] = "L'article '#{@article.title}' a bien été supprimé !"
          redirect_to dashboard_articles_path
        end
        format.js do
        end
      end
    end

    #another update method to update only the published column (boolean)
    def update_published
      @article = Article.find(params[:id])
      if @article.published
        @article.update(published: false)
        redirect_to edit_dashboard_article_path(@article)
        flash[:notice] = "Votre article vient d'être mis hors ligne !"
      else
        @article.update(published: true)
        flash[:notice] = "Votre article vient d'être mis en ligne !"
        redirect_to edit_dashboard_article_path(@article)
      end
    end


    private

    def article_params
      params.require(:article).permit(:title, :description, :content, :published)
    end

    #method to prevent one admin to edit or destroy another admin's articles
    def secret
      @article = Article.find(params[:id])
      @admin = Admin.find(@article.admin_id)
      unless @admin.id == current_admin.id
        flash[:notice] = "Vous n'avez pas le droit d'éditer ou supprimer l'article car vous n'êtes pas l'auteur !"
        redirect_to dashboard_articles_path
      end
    end

  end

end

app/controllers/dashboard/avatars_controller.rb
module Dashboard

  class AvatarsController < ApplicationController

    def create
      @admin = Admin.find(params[:admin_id])
      @admin.avatar.attach(params[:avatar])
      redirect_to edit_dashboard_admin_path(@admin)
    end

    def destroy
      @admin = Admin.find(params[:admin_id])
      @admin.avatar.purge
      redirect_to edit_dashboard_admin_path(@admin)
    end

	end

end

app/controllers/dashboard/categories_controller.rb
module Dashboard

  class CategoriesController < ApplicationController
    before_action :authenticate_admin!

    def index
      @categories = Category.all.order('created_at DESC')
    end

    def show
      @category = Category.find(params[:id])
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:notice] = "La catégorie #{@category.category_name} a été créée !"
        redirect_to dashboard_categories_path
      else
        render "new"
      end
    end

    def edit
      @category = Category.find(params[:id])
    end

    def update
      @category = Category.find(params[:id])
      if @category.update(category_params)
        flash[:notice] = "La catégorie #{@category.category_name} a bien été mise à jour !"
        redirect_to dashboard_categories_path
      else
        render "edit"
      end
    end

    def destroy
      @category = Category.find(params[:id])
      @category.destroy
      respond_to do |format|
        format.html do
          flash[:notice] = "La catégorie a bien été supprimée !"
          redirect_to dashboard_categories_path
        end
        format.js do
        end
      end

    end


    private

    def category_params
      params.require(:category).permit(:category_name)
    end

  end

end

app/controllers/dashboard/contacts_controller.rb
module Dashboard

  class ContactsController < ApplicationController
    before_action :authenticate_admin!

    def index
      @contacts = Contact.all.order('created_at DESC')
    end

    def show
      @contact = Contact.find(params[:id])
    end

  end

end

app/controllers/dashboard/events_controller.rb
module Dashboard

  class EventsController < ApplicationController
    before_action :authenticate_admin!
    before_action :secret, only: [:edit, :update, :destroy]

    def index
      @events = Event.all
      @current_events = Event.where(admin_id: current_admin.id).order('created_at DESC')
    end

    def new
      @event = Event.new
    end

    def create
      @event = Event.new(event_params)
      @event.admin = current_admin
      if @event.save
        flash[:notice] = "Vous venez de créer une nouvelle actualité. Vérifiez les informations avant de la mettre en ligne !"
        redirect_to edit_dashboard_event_path(@event)
      else
        render "new"
      end
    end

    def show
      @event = Event.find(params[:id])
    end

    def edit
      @event = Event.find(params[:id])
    end

    def update
      @event = Event.find(params[:id])
      if @event.update(event_params)
        flash[:notice] = "L'actualité '#{@event.title}'' a bien été éditée !"
        redirect_to dashboard_events_path
      else
        render "edit"
      end
    end

    #another update method to update only the published column (bolean)
    def update_published
      @event = Event.find(params[:id])
			#reverse the published attribute, false become true (online) and true become false (offline)
      if @event.published
        @event.update(published: false)
        redirect_to edit_dashboard_event_path(@event)
        flash[:notice] = "Votre actualité vient d'être mise hors ligne !"
      else
        @event.update(published: true)
        flash[:notice] = "Votre actualité vient d'être mise en ligne !"
        redirect_to edit_dashboard_event_path(@event)
      end
    end

    def destroy
      @event = Event.find(params[:id])
      @event.destroy
      respond_to do |format|
        format.html do
          flash[:notice] = "L'actualité '#{@event.title}'' a bien été supprimée !"
          redirect_to dashboard_events_path
        end
        format.js do
        end
      end
    end


    private

    def event_params
      params.require(:event).permit(:title, :description, :content, :date, :published, :location)
    end

    #method to prevent one admin to edit or destroy another admin's events
    def secret
      @event = Event.find(params[:id])
      @admin = Admin.find(@event.admin_id)
      unless @admin.id == current_admin.id
        flash[:notice] = "Vous n'avez pas le droit d'éditer l'actualité car vous n'êtes pas l'auteur !"
        redirect_to dashboard_events_path
      end
    end

  end

end

app/controllers/dashboard/images_controller.rb
module Dashboard

  class ImagesController < ApplicationController

    def create
      @article = Article.find(params[:article_id])
      @article.image.attach(params[:image])
      redirect_to edit_dashboard_article_path(@article)
    end

    def destroy
      @article = Article.find(params[:article_id])
      @article.image.purge
      redirect_to edit_dashboard_article_path(@article)
    end

  end

end

app/controllers/dashboard/pictures_controller.rb
module Dashboard

  class PicturesController < ApplicationController

    def create
      @project = Project.find(params[:project_id])
      @project.pictures.attach(params[:pictures])
      redirect_to edit_dashboard_project_path(@project)
    end

    def destroy
      @project = Project.find(params[:project_id])
      @pictures = ActiveStorage::Attachment.where(record_id: params[:project_id])
      @pic_to_delete = @pictures.find_by(blob_id: params[:id])
      @pic_to_delete.purge
      redirect_to edit_dashboard_project_path(@project)
    end

  end

end

app/controllers/dashboard/projects_controller.rb
module Dashboard

  class ProjectsController < ApplicationController
    before_action :authenticate_admin!
    before_action :secret, only: [:edit, :update, :destroy]

    def index
      @projects = Project.all
      @current_projects = Project.where(admin_id: current_admin.id).order('created_at DESC')
    end

    def show
      @project = Project.find(params[:id])
    end

    def new
      @project = Project.new
      @categories = Category.all
    end

    def create
      @project = Project.new(project_params)
      @project.admin = current_admin
      @categories = Category.all
      if @project.save
        #unless the case when one admin does not check any box
        unless params[:project][:categories] == nil
          category_array = params[:project][:categories]
          category_array.each do |category|
            @project.categories << Category.find(category)
          end
        end
        flash[:notice] = "Vous venez de créer une nouvelle réalisation. Ajoutez des photos et relisez les informations avant de la mettre en ligne !"
        redirect_to edit_dashboard_project_path(@project)

      else
        render "new"
      end
    end

    def edit
      @project = Project.find(params[:id])
      @categories = Category.all
      @current_categories = @project.categories
    end

    def update
      @project = Project.find(params[:id])
      @categories = Category.all
      @current_categories = @project.categories
      if @project.update(project_params)
				#unless the case when one admin does not check any box
        unless params[:project][:categories] == nil
          category_array = params[:project][:categories]
          #empty @project.categories to remove all the previous categories and take into account the new ones
          @project.categories = []
          category_array.each do |category|
            @project.categories << Category.find(category)
          end
        end
        flash[:notice] = "La réalisation '#{@project.title}' a bien été éditée !"
        redirect_to dashboard_projects_path
      else
        render "edit"
      end
    end

    def destroy
      @project = Project.find(params[:id])
      @project.pictures.purge
      @project.destroy
      respond_to do |format|
        format.html do
          flash[:notice] = "La réalisation '#{@project.title}' a bien été supprimée !"
          redirect_to dashboard_projects_path
        end
        format.js do
        end
      end
    end

    #another update method to update only the published column (bolean)
    def update_published
      @project = Project.find(params[:id])
      if @project.published
        @project.update(published: false)
        redirect_to edit_dashboard_project_path(@project)
        flash[:notice] = "Votre réalisation vient d'être mise hors ligne !"
      else
        @project.update(published: true)
        flash[:notice] = "Votre réalisation vient d'être mise en ligne !"
        redirect_to edit_dashboard_project_path(@project)
      end
    end

    private

    def project_params
      params.require(:project).permit(:title, :description, :content, :date, :published)
    end

		#method to prevent one admin to edit or destroy another admin's projects
    def secret
      @project = Project.find(params[:id])
      @admin = Admin.find(@project.admin_id)
      unless @admin.id == current_admin.id
        flash[:notice] = "Vous n'avez pas le droit d'éditer ou supprimer cette réalisation car vous n'êtes pas l'auteur !"
        redirect_to dashboard_projects_path
      end
    end

  end

end

app/controllers/dashboard/thumbnails_controller.rb
module Dashboard

  class ThumbnailsController < ApplicationController

    def create
      @project = Project.find(params[:project_id])
      @project.thumbnail.attach(params[:thumbnail])
      redirect_to edit_dashboard_project_path(@project)
    end

    def destroy
      @project = Project.find(params[:project_id])
      @project.thumbnail.purge
      redirect_to edit_dashboard_project_path(@project)
    end

  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @categories = Category.all

    #condition to sort projects out depending on their categories (thanks to a params :category in view index)
    if params.has_key?(:category)
      @category = Category.find_by(category_name: params[:category])
      @projects = @category.projects.where(published: true).order('created_at DESC')
    else
      @projects = Project.where(published: true).order('created_at DESC')
    end

  end

  def show
    @project = Project.find(params[:id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/dashboard/projects/destroy.js.erb
var projectToDelete = document.getElementById("project<%=@project.id%>");
projectToDelete.remove();

app/views/dashboard/projects/edit.html.erb
<div class="wrapper gray-wrapper">
  <% if @project.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p class="home-header-font">Nous n'avons pas réussi à créer la réalisation pour la (ou les) raison(s) suivante(s)
        :</p>
      <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
  </div>

  <div class="container-fluid">

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
      <li class="breadcrumb-item active">Mise à jour de la réalisation</li>
      <li class="breadcrumb-item">
        <%= link_to 'Revenir à toutes les réalisations', dashboard_projects_path %>
      </li>
    </ol>

  </div>

  <div class="container inner">

    <div class="row">
      <div class="col-lg-10 offset-lg-1 col-xl-8 offset-xl-2">
        <h2 class="section-title text-center"> Réalisation "<%= @project.title %>"
          <br>Ajout des photos et mise à jour des informations
        </h2>

        <!-- Button for published / unpublished -->
        <center>
          <% if @project.published %>
            <%= link_to 'Prévisualiser', @project, class: 'btn btn-ice home-header-font' %>
            <%= link_to 'Mettre hors ligne', update_published_dashboard_project_path(@project), method: :put, class: 'btn btn-danger home-header-font' %>
          <% elsif @project.published == false && @project.thumbnail.attached? == true %>
            <%= link_to 'Prévisualiser', dashboard_project_path(@project), class: 'btn btn-ice home-header-font' %>
            <%= link_to 'Mettre en ligne', update_published_dashboard_project_path(@project), method: :put, class: 'btn btn-success home-header-font' %>
          <% else %>
            <div class="tooltip-dashboard">
              <%= link_to 'Prévisualiser', dashboard_project_path(@project), class: 'btn btn-ice home-header-font' %>
              <%= link_to 'Mettre en ligne', update_published_dashboard_project_path(@project), method: :put, class: 'btn btn-success disabled home-header-font' %>
              <span class="tooltiptext-dashboard">Ajouter une photo de miniature avant de mettre en ligne !</span>
            </div>
          <% end %>
        </center>
        <!-- /Button for published / unpublished -->

        <div class="space60"></div>

        <!-- Form for active_storage -->
        <center>
          <% if @project.thumbnail.attached? %>
            <% if @project.published %>
              <p class="home-header-font">Photo de miniature de la réalisation </p>
              <%= image_tag @project.thumbnail.variant(resize: "150x150") %> <br><br>
              <div class="tooltip-dashboard">
                <%= link_to 'Changer de photo', dashboard_project_thumbnail_path(@project), method: :delete, class: 'btn btn-ice home-header-font disabled' %>
                <span class="tooltiptext-dashboard">Merci de mettre votre réalisation hors ligne avant de changer la miniature !</span>
              </div>
            <% else %>
              <p class="home-header-font">Photo de miniature de la réalisation </p>
              <%= image_tag @project.thumbnail.variant(resize: "150x150") %> <br><br>
              <%= link_to 'Changer de photo', dashboard_project_thumbnail_path(@project), method: :delete, class: 'btn btn-ice home-header-font' %>
            <% end %>

          <% else %>
            <p class="home-header-font">Ajouter une photo pour la miniature</p>
            <%= form_tag dashboard_project_thumbnails_path(@project), multipart: true do %>
              <%= file_field_tag :thumbnail %>
              <%= submit_tag "Ajouter", class: 'btn btn-ice home-header-font' %>
            <% end %>
            <p>=== Veuillez choisir une miniature pour cette réalisation ===</p>
          <% end %>

          <div class="space60"></div>

          <% if @project.pictures.length == 0 %>
            <p class="home-header-font">Ajouter les photos du diaporama (3 minimum pour une belle mise en page ou aucune
              !)</p>
            <%= form_tag dashboard_project_pictures_path(@project), multipart: true do %>
              <%= file_field_tag 'pictures[]', :multiple => true %>
              <%= submit_tag "Ajouter", class: 'btn btn-ice home-header-font' %>
            <% end %>
            <p>=== Veuillez choisir au minimum 3 photos pour le diaporama de cette réalisation - à sélectionner 1 par 1
              ===</p>

          <% else %>
            <p class="home-header-font">Les photos du diaporama (3 minimum pour une belle mise en page ou aucune !) </p>

            <table>
              <% @project.pictures.each do |image| %>
                <tr>
                  <td>
                    <div class="margin-picture"><%= image_tag image.variant(resize: "150x150") %></div>
                  </td>
                  <td></td>
                  <td>
                    <%= link_to 'Supprimer cette photo', dashboard_project_picture_path(@project, image), method: :delete, class: 'btn btn-ice home-header-font' %>
                    <br><br>
                  </td>
                </tr>
              <% end %>
            </table>
            <p><%= form_tag dashboard_project_pictures_path(@project), multipart: true do %>
                <%= file_field_tag :pictures %>
                <%= submit_tag "Ajouter", class: 'btn btn-ice home-header-font' %>
              <% end %></p>


          <% end %>
        </center>
        <!-- /Form for active_storage -->

        <div class="space90"></div>

        <p class="home-header-font">Si vous souhaitez modifier certaines informations, modifier le formulaire ci-dessous
          et cliquer sur Enregistrer les modifications.</p>
        <div class="space10"></div>
        <h6><strong>Titre de la réalisation</strong></h6>
        <%= form_with model: @project, url: dashboard_project_path, local: true do |f| %>
          <%= f.text_field :title, class: "form-control", placeholder: "Titre" %>
          <div class="space30"></div>
          <h6><strong>Description (en 1 phrase)</strong></h6>
          <%= f.text_area :description, class: "form-control", placeholder: "Description" %>
          <div class="space30"></div>
          <h6><strong>Contenu</strong></h6>
          <%= f.text_area :content, class: "form-control", placeholder: "Contenu", :rows => 6 %>
          <div class="space30"></div>

          <h6><strong>Catégorie</strong></h6>
          <% if @project.categories.length > 0 %>
            <p>La (ou les) catégorie(s) actuelle(s) de la réalisations sont :</p>
            <ul class="nav nav-tabs justify-content-center">
              <% @current_categories.each do |cat| %>
                <li class="nav-item">"<%= cat.category_name %>"</li>
              <% end %>
            </ul>
            <div class="space10"></div>

            <p>Avant de cliquer sur le bouton "Enregistrer les modifications", merci d'indiquer à nouveau les catégories
              que vous souhaitez appliquer en les sélectionnant ci-dessous. Vous pouvez également en
              choisir des nouvelles.</p>

          <% else %>
            <p>Vous n'avez pas encore sélectionné de catégories pour cette réalisation, vous pouvez le faire en cochant
              une ou plusieurs cases ci-dessous.</p>
          <% end %>

          <div class="space10"></div>

          <% i = 0 %>
          <% @categories.each do |category| %>
            <div class="form-group">
              <div class="custom-control custom-checkbox">
                <%= f.check_box :categories, {class: "custom-control-input", id: "customCheck#{i}", multiple: true}, category.id, nil %>
                <label class="custom-control-label" for= <%= "customCheck#{i}" %>><%= category.category_name %></label>
              </div>
            </div>
            <% i = i + 1 %>
          <% end %>
          <div class="space30"></div>
          <%= f.submit "Enregistrer les modifications", class: 'btn btn-ice home-header-font' %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/dashboard/projects/index.html.erb
<div class="container-fluid">

  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">Réalisations</li>
    <li class="breadcrumb-item">
      <%= link_to 'Voir la page Réalisations du site', projects_path %>
    </li>
  </ol>

  <!-- DataTables Example -->
  <div class="card mb-3">
    <div class="card-header">
      <h2 class="section-title text-center">Mes réalisations</h2>
      <p align="center"><%= link_to "Créer une nouvelle réalisation", new_dashboard_project_path, class: "btn btn-ice home-header-font wrap-title" %></p>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
          <tr>
            <th>Titre</th>
            <th>Auteur</th>
            <th>Créée le</th>
            <th>Modifiée le</th>
            <th>Statut</th>
            <th>Voir</th>
            <th>Editer</th>
            <th>Supprimer</th>
          </tr>
          </thead>
          <% if @current_projects.length == 0 %>
            <tr>
              <td colspan="8">
                <center>Vous n'avez pas encore créé de réalisation ! Lancez-vous en cliquant sur le bouton "Créer une
                  nouvelle réalisation."
                </center>
              </td>
          <% else %>
            <% @projects.each do |project| %>
              <% if project.admin == current_admin %>
                <tr id="project<%= project.id %>">
                  <td><%= project.title %>  </td>
                  <td><%= project.admin.pseudo %> </td>
                  <td><%= project.created_at.strftime("%d/%m/%Y") %> </td>
                  <td><%= project.updated_at.strftime("%d/%m/%Y") %> </td>

                  <% if project.published %>
                    <td class="online-bold">En ligne</td>
                  <% else %>
                    <td class="offline-fade">Hors ligne</td>
                  <% end %>

                  <td><%= link_to dashboard_project_path(project.id) do %>
                      <i class="fa fa-search fa-2x d-flex justify-content-center"></i>
                    <% end %>
                  </td>
                  <td><%= link_to edit_dashboard_project_path(project.id) do %>
                      <i class="fa fa-edit fa-2x d-flex justify-content-center green"></i>
                    <% end %>
                  </td>
                  <td> <%= link_to dashboard_project_path(project.id), data: {confirm: "Êtes-vous sûr.e de vouloir supprimer cette réalisation à tout jamais ?"}, method: :delete, remote: true do %>
                      <i class="fa fa-trash fa-2x d-flex justify-content-center red"></i>
                    <% end %>
                  </td>
                </tr>
              <% else %>
              <% end %>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
  </div>

  <!-- DataTables Example -->
  <div class="card mb-3">
    <div class="card-header">
      <h2 class="section-title text-center">Les autres réalisations</h2>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
          <tr>
            <th>Titre</th>
            <th>Auteur</th>
            <th>Créée le</th>
            <th>Modifiée le</th>
            <th>Statut</th>
            <th>Voir</th>
          </tr>
          </thead>
          <% @projects.each do |project| %>
            <% unless project.admin == current_admin %>
              <tr>
                <td><%= project.title %>  </td>
                <td><%= project.admin.pseudo %> </td>
                <td><%= project.created_at.strftime("%d/%m/%Y") %> </td>
                <td><%= project.updated_at.strftime("%d/%m/%Y") %> </td>

                <% if project.published %>
                  <td class="online-bold">En ligne</td>
                <% else %>
                  <td class="offline-fade">Hors ligne</td>
                <% end %>

                <td><%= link_to dashboard_project_path(project.id) do %>
                    <i class="fa fa-search fa-2x d-flex justify-content-center"></i>
                  <% end %>
                </td>
              </tr>
            <% else %>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
  </div>

</div>