config/routes.rb
Rails.application.routes.draw do
  
	root to: 'static_pages#home'

  devise_for :admins

#routes for visitors' website
  resources :articles, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :projects, only: [:index, :show]
  resources :contacts, only: [:new, :create]

#routes for admins' dashboard
  namespace :dashboard do

    resources :categories
    resources :contacts, only: [:index, :show]

    resources :admins, only: [:show, :edit, :update] do
      #for active_storage 
      resources :avatars
    end
    resources :events do
      # to define another update methode (dedicated to online / offline mode)
      member do    
        put :update_published
      end
    end

    resources :projects do
      #for active_storage 
      resources :pictures, only: [:create, :destroy]
      resources :thumbnails, only: [:create, :destroy]
      # to define another update methode (dedicated to online / offline mode)
      member do
        put :update_published
      end
    end

    resources :articles do
      #for active_storage 
      resources :images, only: [:create, :destroy]
      # to define another update methode (dedicated to online / offline mode)
      member do
        put :update_published
      end
    end
    
  end

end

app/models/event.rb
class Event < ApplicationRecord

  validates :title, presence: {message: "Merci d'indiquer le titre de l'actualité."}, length: {minimum: 2, message: "Le titre doit faire plus de 2 caractères."}
  validates :description, presence: {message: "Merci d'indiquer la description de l'actualité."}, length: {maximum: 200, message: "La description doit faire moins de 200 caractères maximum."}
  validates :content, presence: {message: "Merci d'indiquer le contenu de l'actualité."}

  belongs_to :admin

end

app/controllers/dashboard/admins_controller.rb
module Dashboard

  class AdminsController < ApplicationController
    before_action :authenticate_admin!
    before_action :secret, only: [:show]

    def show
      @admin = Admin.find(params[:id])
    end

    def edit
      @admin = Admin.find(params[:id])
    end

    def update
      @admin = Admin.find(params[:id])
      if @admin.update(admin_params)
        redirect_to edit_dashboard_admin_path(@admin)
        flash[:notice] = "Modifications prises en compte!"
      else
        render "edit"
      end
    end

    private

    def admin_params
      params.require(:admin).permit(:first_name, :last_name, :pseudo, :description, :speciality, :display)
    end

    #method to prevent one admin to go on another admin's dashboard
    def secret
      @admin = Admin.find(params[:id])
      unless @admin.id == current_admin.id
        flash[:notice] = "Vous n'avez pas les droits d'accès au dashboard d'un autre admin!"
        redirect_to admin_path(current_admin)
      end
    end

  end

end

app/controllers/dashboard/application_controller.rb
module Dashboard

	class ApplicationController < ::ApplicationController
	end

end

app/controllers/dashboard/articles_controller.rb
module Dashboard

  class ArticlesController < ApplicationController
    before_action :authenticate_admin!
    before_action :secret, only: [:edit, :update, :destroy]

    def index
      @articles = Article.all.order('created_at DESC')
      @current_articles = Article.where(admin_id: current_admin.id)
    end

    def show
      @article = Article.find(params[:id])
    end

    def new
      @article = Article.new
    end

    def create
      @article = Article.new(article_params)
      @article.admin = current_admin
      if @article.save
        flash[:notice] = "Vous venez de créer un nouvel article. Ajoutez une photo et relisez les informations avant le mettre en ligne !"
        redirect_to edit_dashboard_article_path(@article)
      else
        render "new"
      end
    end

    def edit
      @article = Article.find(params[:id])
    end

    def update
      @article = Article.find(params[:id])
      if @article.update(article_params)
        flash[:notice] = "L'article '#{@article.title}' a bien été édité !"
        redirect_to dashboard_articles_path
      else
        render "edit"
      end
    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      respond_to do |format|
        format.html do
          flash[:notice] = "L'article '#{@article.title}' a bien été supprimé !"
          redirect_to dashboard_articles_path
        end
        format.js do
        end
      end
    end

    #another update method to update only the published column (boolean)
    def update_published
      @article = Article.find(params[:id])
      if @article.published
        @article.update(published: false)
        redirect_to edit_dashboard_article_path(@article)
        flash[:notice] = "Votre article vient d'être mis hors ligne !"
      else
        @article.update(published: true)
        flash[:notice] = "Votre article vient d'être mis en ligne !"
        redirect_to edit_dashboard_article_path(@article)
      end
    end


    private

    def article_params
      params.require(:article).permit(:title, :description, :content, :published)
    end

    #method to prevent one admin to edit or destroy another admin's articles
    def secret
      @article = Article.find(params[:id])
      @admin = Admin.find(@article.admin_id)
      unless @admin.id == current_admin.id
        flash[:notice] = "Vous n'avez pas le droit d'éditer ou supprimer l'article car vous n'êtes pas l'auteur !"
        redirect_to dashboard_articles_path
      end
    end

  end

end

app/controllers/dashboard/avatars_controller.rb
module Dashboard

  class AvatarsController < ApplicationController

    def create
      @admin = Admin.find(params[:admin_id])
      @admin.avatar.attach(params[:avatar])
      redirect_to edit_dashboard_admin_path(@admin)
    end

    def destroy
      @admin = Admin.find(params[:admin_id])
      @admin.avatar.purge
      redirect_to edit_dashboard_admin_path(@admin)
    end

	end

end

app/controllers/dashboard/categories_controller.rb
module Dashboard

  class CategoriesController < ApplicationController
    before_action :authenticate_admin!

    def index
      @categories = Category.all.order('created_at DESC')
    end

    def show
      @category = Category.find(params[:id])
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:notice] = "La catégorie #{@category.category_name} a été créée !"
        redirect_to dashboard_categories_path
      else
        render "new"
      end
    end

    def edit
      @category = Category.find(params[:id])
    end

    def update
      @category = Category.find(params[:id])
      if @category.update(category_params)
        flash[:notice] = "La catégorie #{@category.category_name} a bien été mise à jour !"
        redirect_to dashboard_categories_path
      else
        render "edit"
      end
    end

    def destroy
      @category = Category.find(params[:id])
      @category.destroy
      respond_to do |format|
        format.html do
          flash[:notice] = "La catégorie a bien été supprimée !"
          redirect_to dashboard_categories_path
        end
        format.js do
        end
      end

    end


    private

    def category_params
      params.require(:category).permit(:category_name)
    end

  end

end

app/controllers/dashboard/contacts_controller.rb
module Dashboard

  class ContactsController < ApplicationController
    before_action :authenticate_admin!

    def index
      @contacts = Contact.all.order('created_at DESC')
    end

    def show
      @contact = Contact.find(params[:id])
    end

  end

end

app/controllers/dashboard/events_controller.rb
module Dashboard

  class EventsController < ApplicationController
    before_action :authenticate_admin!
    before_action :secret, only: [:edit, :update, :destroy]

    def index
      @events = Event.all
      @current_events = Event.where(admin_id: current_admin.id).order('created_at DESC')
    end

    def new
      @event = Event.new
    end

    def create
      @event = Event.new(event_params)
      @event.admin = current_admin
      if @event.save
        flash[:notice] = "Vous venez de créer une nouvelle actualité. Vérifiez les informations avant de la mettre en ligne !"
        redirect_to edit_dashboard_event_path(@event)
      else
        render "new"
      end
    end

    def show
      @event = Event.find(params[:id])
    end

    def edit
      @event = Event.find(params[:id])
    end

    def update
      @event = Event.find(params[:id])
      if @event.update(event_params)
        flash[:notice] = "L'actualité '#{@event.title}'' a bien été éditée !"
        redirect_to dashboard_events_path
      else
        render "edit"
      end
    end

    #another update method to update only the published column (bolean)
    def update_published
      @event = Event.find(params[:id])
			#reverse the published attribute, false become true (online) and true become false (offline)
      if @event.published
        @event.update(published: false)
        redirect_to edit_dashboard_event_path(@event)
        flash[:notice] = "Votre actualité vient d'être mise hors ligne !"
      else
        @event.update(published: true)
        flash[:notice] = "Votre actualité vient d'être mise en ligne !"
        redirect_to edit_dashboard_event_path(@event)
      end
    end

    def destroy
      @event = Event.find(params[:id])
      @event.destroy
      respond_to do |format|
        format.html do
          flash[:notice] = "L'actualité '#{@event.title}'' a bien été supprimée !"
          redirect_to dashboard_events_path
        end
        format.js do
        end
      end
    end


    private

    def event_params
      params.require(:event).permit(:title, :description, :content, :date, :published, :location)
    end

    #method to prevent one admin to edit or destroy another admin's events
    def secret
      @event = Event.find(params[:id])
      @admin = Admin.find(@event.admin_id)
      unless @admin.id == current_admin.id
        flash[:notice] = "Vous n'avez pas le droit d'éditer l'actualité car vous n'êtes pas l'auteur !"
        redirect_to dashboard_events_path
      end
    end

  end

end

app/controllers/dashboard/images_controller.rb
module Dashboard

  class ImagesController < ApplicationController

    def create
      @article = Article.find(params[:article_id])
      @article.image.attach(params[:image])
      redirect_to edit_dashboard_article_path(@article)
    end

    def destroy
      @article = Article.find(params[:article_id])
      @article.image.purge
      redirect_to edit_dashboard_article_path(@article)
    end

  end

end

app/controllers/dashboard/pictures_controller.rb
module Dashboard

  class PicturesController < ApplicationController

    def create
      @project = Project.find(params[:project_id])
      @project.pictures.attach(params[:pictures])
      redirect_to edit_dashboard_project_path(@project)
    end

    def destroy
      @project = Project.find(params[:project_id])
      @pictures = ActiveStorage::Attachment.where(record_id: params[:project_id])
      @pic_to_delete = @pictures.find_by(blob_id: params[:id])
      @pic_to_delete.purge
      redirect_to edit_dashboard_project_path(@project)
    end

  end

end

app/controllers/dashboard/projects_controller.rb
module Dashboard

  class ProjectsController < ApplicationController
    before_action :authenticate_admin!
    before_action :secret, only: [:edit, :update, :destroy]

    def index
      @projects = Project.all
      @current_projects = Project.where(admin_id: current_admin.id).order('created_at DESC')
    end

    def show
      @project = Project.find(params[:id])
    end

    def new
      @project = Project.new
      @categories = Category.all
    end

    def create
      @project = Project.new(project_params)
      @project.admin = current_admin
      @categories = Category.all
      if @project.save
        #unless the case when one admin does not check any box
        unless params[:project][:categories] == nil
          category_array = params[:project][:categories]
          category_array.each do |category|
            @project.categories << Category.find(category)
          end
        end
        flash[:notice] = "Vous venez de créer une nouvelle réalisation. Ajoutez des photos et relisez les informations avant de la mettre en ligne !"
        redirect_to edit_dashboard_project_path(@project)

      else
        render "new"
      end
    end

    def edit
      @project = Project.find(params[:id])
      @categories = Category.all
      @current_categories = @project.categories
    end

    def update
      @project = Project.find(params[:id])
      @categories = Category.all
      @current_categories = @project.categories
      if @project.update(project_params)
				#unless the case when one admin does not check any box
        unless params[:project][:categories] == nil
          category_array = params[:project][:categories]
          #empty @project.categories to remove all the previous categories and take into account the new ones
          @project.categories = []
          category_array.each do |category|
            @project.categories << Category.find(category)
          end
        end
        flash[:notice] = "La réalisation '#{@project.title}' a bien été éditée !"
        redirect_to dashboard_projects_path
      else
        render "edit"
      end
    end

    def destroy
      @project = Project.find(params[:id])
      @project.pictures.purge
      @project.destroy
      respond_to do |format|
        format.html do
          flash[:notice] = "La réalisation '#{@project.title}' a bien été supprimée !"
          redirect_to dashboard_projects_path
        end
        format.js do
        end
      end
    end

    #another update method to update only the published column (bolean)
    def update_published
      @project = Project.find(params[:id])
      if @project.published
        @project.update(published: false)
        redirect_to edit_dashboard_project_path(@project)
        flash[:notice] = "Votre réalisation vient d'être mise hors ligne !"
      else
        @project.update(published: true)
        flash[:notice] = "Votre réalisation vient d'être mise en ligne !"
        redirect_to edit_dashboard_project_path(@project)
      end
    end

    private

    def project_params
      params.require(:project).permit(:title, :description, :content, :date, :published)
    end

		#method to prevent one admin to edit or destroy another admin's projects
    def secret
      @project = Project.find(params[:id])
      @admin = Admin.find(@project.admin_id)
      unless @admin.id == current_admin.id
        flash[:notice] = "Vous n'avez pas le droit d'éditer ou supprimer cette réalisation car vous n'êtes pas l'auteur !"
        redirect_to dashboard_projects_path
      end
    end

  end

end

app/controllers/dashboard/thumbnails_controller.rb
module Dashboard

  class ThumbnailsController < ApplicationController

    def create
      @project = Project.find(params[:project_id])
      @project.thumbnail.attach(params[:thumbnail])
      redirect_to edit_dashboard_project_path(@project)
    end

    def destroy
      @project = Project.find(params[:project_id])
      @project.thumbnail.purge
      redirect_to edit_dashboard_project_path(@project)
    end

  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.where(published: true).order('created_at DESC')
  end

  def show
    @event = Event.find(params[:id])
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/dashboard/events/destroy.js.erb
var eventToDelete = document.getElementById("event<%=@event.id%>");
eventToDelete.remove();

app/views/dashboard/events/edit.html.erb
<div class="wrapper gray-wrapper">
  <% if @event.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p class="home-header-font">Nous n'avons pas réussi à créer l'actualité pour la (ou les) raison(s) suivante(s)
        :</p>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>

      </ul>
  <% end %>
  </div>

  <div class="container-fluid">

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
      <li class="breadcrumb-item active">Mise à jour de l'actualité</li>
      <li class="breadcrumb-item">
        <%= link_to 'Revenir à toutes les actualités', dashboard_events_path %>
      </li>
    </ol>

  </div>

  <div class="container inner">
    <div class="row">
      <div class="col-lg-10 offset-lg-1 col-xl-8 offset-xl-2">
        <h2 class="section-title text-center">Actualité "<%= @event.title %>"</h2>

        <!-- Button for published / unpublished -->
        <center>
          <% if @event.published %>
            <%= link_to 'Prévisualiser', dashboard_event_path(@event), class: 'btn btn-ice home-header-font' %>
            <%= link_to 'Mettre hors ligne', update_published_dashboard_event_path(@event), method: :put, class: 'btn btn-danger home-header-font' %>
          <% else %>
            <%= link_to 'Prévisualiser', dashboard_event_path(@event), class: 'btn btn-ice home-header-font' %>
            <%= link_to 'Mettre en ligne', update_published_dashboard_event_path(@event), method: :put, class: 'btn btn-success home-header-font' %>
          <% end %>
        </center>
        <!-- /Button for published / unpublished -->

        <div class="space60"></div>

        <p class="home-header-font">Si vous souhaitez modifier certaines informations, modifier le formulaire ci-dessous
          et cliquer sur Enregistrer les modifications.</p>
        <div class="space10"></div>
        <h6><b>Titre de l'actualité</b></h6>
        <%= form_with model: @event, url: dashboard_event_path, local: true do |f| %>
          <%= f.text_field :title, class: "form-control", placeholder: "Titre" %>
          <div class="space30"></div>
          <h6><b>Description rapide</b></h6>
          <%= f.text_area :description, class: "form-control", placeholder: "Description (en 1 phrase)" %>
          <div class="space30"></div>
          <h6><b>Détails de l'actualité</b></h6>
          <%= f.text_area :content, class: "form-control", placeholder: "Détails", :rows => 6 %>
          <div class="space30"></div>
          <h6><b>Adresse de l'événement (si nécessaire)</b></h6>
          <%= f.text_area :location, class: "form-control", placeholder: "Ville" %>
          <div class="space30"></div>
          <h6><b>Date et heure de l'événement (si nécessaire) </b></h6>
          <%= f.text_field :date, class: "form-control", placeholder: "Date et heure" %>
          <br><br>
          <%= f.submit "Modifier les informations", class: 'btn btn-ice home-header-font' %>
        <% end %>

        <div class="space30"></div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/events/index.html.erb
<div class="container-fluid">

  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">Actualités</li>
    <li class="breadcrumb-item">
      <%= link_to 'Voir la page Actualités du site', events_path %>
    </li>
  </ol>

  <!-- DataTables Example -->
  <div class="card mb-3">
    <div class="card-header">
      <h2 class="section-title text-center">Mes actualités</h2>
      <p align="center"><%= link_to "Créer une nouvelle actualité", new_dashboard_event_path, class: "btn btn-ice home-header-font wrap-title" %></p>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
          <tr>
            <th>Titre</th>
            <th>Auteur</th>
            <th>Créée le</th>
            <th>Modifiée le</th>
            <th>Statut</th>
            <th>Voir</th>
            <th>Editer</th>
            <th>Supprimer</th>
          </tr>
          </thead>
          <% if @current_events.length == 0 %>
            <tr>
              <td colspan="8">
                <center>Vous n'avez pas encore créé d'actualité ! Lancez-vous en cliquant sur le bouton "Créer une
                  nouvelle actualité."
                </center>
              </td>
          <% else %>
            <% @events.each do |event| %>
              <% if event.admin == current_admin %>
                <tr id="event<%= event.id %>">
                  <td><%= event.title %>  </td>
                  <td><%= event.admin.pseudo %> </td>
                  <td><%= event.created_at.strftime("%d/%m/%Y") %> </td>
                  <td><%= event.updated_at.strftime("%d/%m/%Y") %> </td>

                  <% if event.published %>
                    <td class="online-bold">En ligne</td>
                  <% else %>
                    <td class="offline-fade">Hors ligne</td>
                  <% end %>

                  <td><%= link_to dashboard_event_path(event.id) do %>
                      <i class="fa fa-search fa-2x d-flex justify-content-center"></i>
                    <% end %>
                  </td>
                  <td><%= link_to edit_dashboard_event_path(event.id) do %>
                      <i class="fa fa-edit fa-2x d-flex justify-content-center green"></i>
                    <% end %>
                  </td>
                  <td><%= link_to dashboard_event_path(event.id), data: {confirm: "Êtes-vous sûr.e de vouloir supprimer cette actualité à tout jamais ?"}, method: :delete, remote: true do %>
                      <i class="fa fa-trash fa-2x d-flex justify-content-center red"></i>
                    <% end %>
                  </td>
                </tr>
              <% else %>
              <% end %>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
  </div>

  <!-- DataTables Example -->
  <div class="card mb-3">
    <div class="card-header">
      <h2 class="section-title text-center">Les autres actualités</h2>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
          <tr>
            <th>Titre</th>
            <th>Auteur</th>
            <th>Créée le</th>
            <th>Modifiée le</th>
            <th>Statut</th>
            <th>Voir</th>
          </tr>
          </thead>
          <% @events.each do |event| %>
            <% unless event.admin == current_admin %>
              <tr>
                <td><%= event.title %>  </td>
                <td><%= event.admin.pseudo %> </td>
                <td><%= event.created_at.strftime("%d/%m/%Y") %> </td>
                <td><%= event.updated_at.strftime("%d/%m/%Y") %> </td>

                <% if event.published %>
                  <td class="online-bold">En ligne</td>
                <% else %>
                  <td class="offline-fade">Hors ligne</td>
                <% end %>

                <td><%= link_to dashboard_event_path(event.id) do %>
                    <i class="fa fa-search fa-2x d-flex justify-content-center"></i>
                  <% end %>
                </td>
              </tr>
            <% else %>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
  </div>

</div>

app/views/dashboard/events/new.html.erb
<div class="wrapper gray-wrapper">
  <% if @event.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p class="home-header-font">Nous n'avons pas réussi à créer l'actualité pour la (ou les) raison(s) suivante(s)
        :</p>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>

      </ul>
  <% end %>
  </div>
  <div class="container inner">
    <div class="row">
      <div class="col-lg-10 offset-lg-1 col-xl-8 offset-xl-2">
        <h2 class="section-title text-center">Création d'une actualité</h2>
        <p class="home-header-font">Remplir le formulaire ci-dessous puis cliquer sur Enregistrer les informations.</p>
        <div class="space40"></div>
        <h6><b>Titre de l'actualité</b></h6>
        <%= form_with model: @event, url: dashboard_events_path, local: true do |f| %>
          <%= f.text_field :title, class: "form-control", placeholder: "Titre" %>
          <div class="space30"></div>
          <h6><b>Description rapide</b></h6>
          <%= f.text_area :description, class: "form-control", placeholder: "Description (en 1 phrase)" %>
          <div class="space30"></div>
          <h6><b>Détails de l'actualité</b></h6>
          <%= f.text_area :content, class: "form-control", placeholder: "Détails", :rows => 6 %>
          <div class="space30"></div>
          <h6><b>Adresse de l'événement (si nécessaire)</b></h6>
          <%= f.text_area :location, class: "form-control", placeholder: "Adresse" %>
          <div class="space30"></div>
          <h6><b>Date et heure de l'événement (si nécéssaire)</b></h6>
          <%= f.text_field :date, class: "form-control", placeholder: "Date et heure" %><br>
          <br>

          <%= f.submit "Enregistrer les informations", class: "btn btn-ice home-header-font" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/dashboard/events/show.html.erb
<div class="content-wrapper">
  <!-- /.wrapper -->
  <div class="wrapper light-wrapper">
    <p class="back-link"><%= link_to "Toutes les actualités", events_path, class: "more more-inverse online-bold" %></p>
    <div class="container container mt-20 mb-90">
      <div class="row">
        <div class="col-lg-8 offset-lg-2">
          <div class="blog classic-view">
            <div class="post">
              <h1 class="post-title text-center"><%= @event.title %></h1>
              <div class="space10"></div>
              <p class="text-center">
                <strong><%= @event.description %></strong>
              </p>
              <div class="space10"></div>
              <div class="post-content">
                <p class="text"><%= simple_format(@event.content) %></p>
                <div class="space10"></div>
                <div class="meta tags mb-10 text-center title-color">
                  <h6 class="date"><%= @event.date %></h6>
                  <h6 class="comments"><%= @event.location %></h6></div>
              </div>
              <!-- /.post-content -->
            </div>
          </div>
        </div>
        <div class="space40"></div>
        <!-- /.post -->
      </div>
      <!--/.row -->
    </div>
    <!-- /.container -->
  </div>
  <!-- /.wrapper -->
</div>