config/routes.rb
Rails.application.routes.draw do
  
	root to: 'static_pages#home'

  devise_for :admins

#routes for visitors' website
  resources :articles, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :projects, only: [:index, :show]
  resources :contacts, only: [:new, :create]

#routes for admins' dashboard
  namespace :dashboard do

    resources :categories
    resources :contacts, only: [:index, :show]

    resources :admins, only: [:show, :edit, :update] do
      #for active_storage 
      resources :avatars
    end
    resources :events do
      # to define another update methode (dedicated to online / offline mode)
      member do    
        put :update_published
      end
    end

    resources :projects do
      #for active_storage 
      resources :pictures, only: [:create, :destroy]
      resources :thumbnails, only: [:create, :destroy]
      # to define another update methode (dedicated to online / offline mode)
      member do
        put :update_published
      end
    end

    resources :articles do
      #for active_storage 
      resources :images, only: [:create, :destroy]
      # to define another update methode (dedicated to online / offline mode)
      member do
        put :update_published
      end
    end
    
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :pseudo, presence: {message: "Merci d'indiquer un pseudo."}, length: {minimum: 2}

  has_many :projects, dependent: :delete_all
  has_many :articles, dependent: :delete_all
  has_many :events, dependent: :delete_all
  has_one_attached :avatar, dependent: :delete_all

  after_create :welcome_send

  def welcome_send
    AdminMailer.welcome_email(self).deliver_now
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  validates :title, presence: {message: "Merci d'indiquer le titre de l'article."}, length: {minimum: 2, message: "Le titre doit faire plus de 2 caractères."}
  validates :description, presence: {message: "Merci d'indiquer la description de l'article."}, length: {maximum: 200, message: "La description doit faire moins de 200 caractères maximum."}
  validates :content, presence: {message: "Merci d'indiquer le contenu de l'article."}

  belongs_to :admin
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_one_attached :image

end

app/models/category.rb
class Category < ApplicationRecord

  validates :category_name, presence: {message: "Merci d'indiquer un titre à la catégorie."}

  has_many :project_categories
  has_many :projects, through: :project_categories

end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :email, presence: true, format: {with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Merci d'indiquer une adresse email valide."}
  validates :name, presence: {message: "Merci d'indiquer votre nom et prénom."}
  validates :subject, presence: {message: "Merci d'indiquer l'objet de la demande."}
  validates :content, presence: {message: "Merci de compléter le contenu du message."}
  after_create :contact_request

  def contact_request
    AdminMailer.contact_email(self).deliver_now
  end

end
    

app/models/event.rb
class Event < ApplicationRecord

  validates :title, presence: {message: "Merci d'indiquer le titre de l'actualité."}, length: {minimum: 2, message: "Le titre doit faire plus de 2 caractères."}
  validates :description, presence: {message: "Merci d'indiquer la description de l'actualité."}, length: {maximum: 200, message: "La description doit faire moins de 200 caractères maximum."}
  validates :content, presence: {message: "Merci d'indiquer le contenu de l'actualité."}

  belongs_to :admin

end

app/models/project.rb
class Project < ApplicationRecord

  validates :title, presence: {message: "Merci d'indiquer le titre de la réalisation."}, length: {minimum: 2, message: "Le titre doit faire plus de 2 caractères."}
  validates :description, presence: {message: "Merci d'indiquer la description de la réalisation."}, length: {maximum: 200, message: "La description doit faire moins de 200 caractères maximum."}
  validates :content, presence: {message: "Merci d'indiquer le contenu de la réalisation."}

  belongs_to :admin
  has_many :project_categories
  has_many :categories, through: :project_categories
  has_one_attached :thumbnail
  has_many_attached :pictures

end

app/models/project_category.rb
class ProjectCategory < ApplicationRecord

  belongs_to :project
  belongs_to :category

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for_flash(type)
    case type
    when 'notice' then
      "alert-info"
    when 'success' then
      "alert-success"
    when 'error' then
      "alert-danger"
    when 'alert' then
      "alert-warning"
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/thumbnails_helper.rb
module ThumbnailsHelper
end

app/views/layouts/_dashboard_footer.html.erb
<footer class="sticky-footer">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Espace Administrateur - Oeil de biche</span>
    </div>
  </div>
</footer>

app/views/layouts/_dashboard_navbar.html.erb
<div class="content-wrapper">
  <nav class="navbar nav-wrapper-dark inverse-text navbar-expand-lg center justify-content-between">
    <div class="navbar-header">
      <%= link_to 'Espace Administrateur', dashboard_admin_path(current_admin), class: "navbar-brand text-color" %>
      <div class="navbar-hamburger ml-auto d-lg-none d-xl-none">
        <button class="hamburger animate" data-toggle="collapse" data-target=".navbar-collapse"><span></span></button>
      </div>
    </div>
    <div class="collapse navbar-collapse">
      <div class="navbar-nav-wrapper">
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Revenir à l'accueil du site", root_path, class: 'nav-link no-letter-spacing' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Se déconnecter', destroy_admin_session_path, method: :delete, class: 'nav-link no-letter-spacing' %>
          </li>
        </ul>
      </div>
      <!-- /.navbar-nav-wrapper -->
    </div>
    <!-- /.navbar-collapse -->
  </nav>
</div>

app/views/layouts/_dashboard_sidebar.html.erb
<ul class="sidebar navbar-nav no-letter-spacing">
  <li class="nav-item">
    <%= link_to dashboard_admin_path(current_admin), class: "nav-link no-letter-spacing" do %>
      <i class="fa fa-home"></i>
      <span>Accueil</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to dashboard_projects_path, class: "nav-link no-letter-spacing" do %>
      <i class="fa fa-image"></i>
      <span>Réalisations</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to dashboard_categories_path, class: "nav-link no-letter-spacing" do %>
      <i class="fa fa-hashtag"></i>
      <span>Catégories</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to dashboard_articles_path, class: "nav-link no-letter-spacing" do %>
      <i class="fa fa-edit"></i>
      <span>Articles</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to dashboard_events_path, class: "nav-link no-letter-spacing" do %>
      <i class="fa fa-calendar"></i>
      <span>Actualités</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to dashboard_contacts_path, class: "nav-link no-letter-spacing" do %>
      <i class="fa fa-envelope"></i>
      <span>Messages reçus</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to edit_dashboard_admin_path(current_admin), class: "nav-link no-letter-spacing" do %>
      <i class="fa fa-user-circle"></i>
      <span>Mes informations</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to edit_admin_registration_path, class: "nav-link no-letter-spacing" do %>
      <i class="fa fa-unlock-alt"></i>
      <span>Mon compte</span>
    <% end %>
  </li>
</ul>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert" style="margin-bottom: 0px;">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- /.wrapper -->
<footer class="dark-wrapper">
  <div class="container inner pt-60 pb-30 text-center text-color">
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <div class="row">
          <div class="col-md-4">
            <div class="widget">
              <h3 class="widget-title footer-bold">Localisation</h3>
              <address class="mb-0">
                1 route de la Pesse<br/>
                39370 L'Embossieux
              </address>
            </div>
            <!-- /.widget -->
          </div>
          <!-- /column -->
          <div class="col-md-4">
            <div class="widget">
              <h3 class="widget-title footer-bold">Nous suivre</h3>
              <ul class="social social-mute social-s">
                <li>
                  <%= link_to "https://www.facebook.com/oeil.debiche.739" do %>
                    <i class="fa fa-facebook fa-2x"></i>
                  <% end %>
                </li>
                <li>
                  <%= link_to "https://www.youtube.com/channel/UCj3lkjkrwOtzATmIH1OOmGw?disable_polymer=true" do %>
                    <i class="fa fa-youtube fa-2x"></i>
                  <% end %>
                </li>
              </ul>
              <div class="space40"></div>
              <% if admin_signed_in? %>
                <%= link_to 'Se déconnecter', destroy_admin_session_path, method: :delete, class: 'btn btn-danger' %>
              <% else %>
                <%= link_to "Espace admin", new_admin_session_path, class: "btn btn-ice" %>
              <% end %>
            </div>
            <!-- /.widget -->
          </div>
          <!-- /column -->
          <div class="col-md-4">
            <div class="widget">
              <h3 class="widget-title footer-bold">Contact</h3>
              <address class="mb-0">
                <%= link_to "bamby.boutique.thp@gmail.com", new_contact_path, class: 'nocolor' %><br/>
                06.70.54.32.11
              </address>
            </div>
            <!-- /.widget -->
          </div>
          <!-- /column -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /column -->
    </div>
    <!-- /.row -->
    <div class="space40"></div>
    <p class="text-center">© 2019 Oeil de Biche. Tous droits réservés.</p>
  </div>
  <!-- /.container -->
</footer>

app/views/layouts/_header.html.erb
<div class="content-wrapper">
  <nav class="navbar transparent absolute nav-wrapper-dark inverse-text navbar-expand-lg center justify-content-between">
    <div class="container">
      <div class="navbar-header">
        <div class="navbar-brand d-lg-none d-xl-none"><%= link_to root_path do %><%= image_tag('logos/logo1.png', class: '', alt: '') %>
          <% end %>
        </div>
        <div class="navbar-hamburger ml-auto d-lg-none d-xl-none">
          <button class="hamburger animate" data-toggle="collapse" data-target=".navbar-collapse">
            <span></span></button>
        </div>
      </div>
      <!-- /.navbar-header -->
      <div class="collapse navbar-collapse">
        <div class="navbar-nav-wrapper navbar-left">
          <ul class="nav navbar-nav mr-auto">
            <li class="nav-item dropdown"><%= link_to 'L\'Association', root_path, class: 'nav-link dropdown-toggle bold-text' %>
              <ul class="dropdown-menu dropdown-menu-left border-top-line">
                <li class="nav-item"><%= link_to 'Qui sommes-nous ?', root_path(@root, anchor: 'association'), class: 'dropdown-item text-color hover-color' %></li>
                <li class="nav-item"><%= link_to 'Nos missions', root_path(@root, anchor: 'mission'), class: 'dropdown-item text-color hover-color' %></li>
                <li class="nav-item"><%= link_to 'Notre équipe', root_path(@root, anchor: 'team'), class: 'dropdown-item text-color hover-color' %></li>
                <li class="nav-item"><%= link_to 'Nos principales réalisations', root_path(@root, anchor: 'realisation'), class: 'dropdown-item text-color hover-color' %></li>
                <li class="nav-item"><%= link_to 'Notre matériel', root_path(@root, anchor: 'equipment'), class: 'dropdown-item text-color hover-color' %></li>
              </ul>
            </li>
            <li class="nav-item"><%= link_to 'Réalisations', projects_path, class: 'nav-link bold-text' %></li>
          </ul>
        </div>
        <div class="navbar-brand d-none d-lg-block"><%= link_to root_path do %><%= image_tag('logos/logo1.png', class: 'img-brand', alt: '') %>
          <% end %>
        </div>
        <div class="navbar-nav-wrapper">
          <ul class="nav navbar-nav ml-auto navbar-right">
            <li class="nav-item"><%= link_to 'Actualités', events_path, class: 'nav-link bold-text' %></li>
            <li class="nav-item"><%= link_to 'Blog', articles_path, class: 'nav-link bold-text' %></li>
            <li class="nav-item"><%= link_to 'Contact', new_contact_path, class: 'nav-link bold-text' %></li>
            <% if admin_signed_in? %>
              <li class="nav-item"><%= link_to 'Espace Admin', dashboard_admin_path(current_admin), class: 'nav-link bg-ice dashboard-btn dashboard-text bold-text' %></li>
            <% end %>
          </ul>
        </div>
        <!-- /.navbar-nav-wrapper -->
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>
  <!-- /.navbar -->
  <div class="rev_slider_wrapper fullscreen-container">
    <div id="slider" class="rev_slider fullscreenbanner bg-dark" data-version="5.4.7">
      <ul>
        <li data-transition="fade" data-thumb="<%= image_path("header/header1.jpg") %>"><%= image_tag('header/header1.jpg', class: '', alt: '') %>
          <div
            class="tp-caption font-weight-500 text-uppercase color-white text-center home-header-font"
            data-x="center"
            data-y="middle"
            data-voffset="['-75','-75','-75','-75']"
            data-fontsize="['16','16','16','16']"
            data-lineheight="['26','26','26','26']"
            data-width="['600','600','600','600']"
            data-textalign="['center','center','center','center']"
            data-whitespace="['normal','normal','normal','normal']"
            data-frames='[{"from":"y:-50px;sX:2;sY:2;opacity:0;","speed":1000,"to":"o:1;","delay":1000,"ease":"Power4.easeOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]'
            data-startslide="0"
            data-endslide="3"
            data-responsive="on"
            data-responsive_offset="on"
            style="z-index: 9; letter-spacing: 3px;">Association Oeil de Biche
          </div>
          <div
            class="tp-caption font-weight-700 color-white text-center"
            data-x="center"
            data-y="middle"
            data-voffset="['0','0','0','0']"
            data-fontsize="['55','55','45','35']"
            data-lineheight="['65','65','55','45']"
            data-width="['900','900','700','700']"
            data-textalign="['center','center','center','center']"
            data-whitespace="['normal','normal','normal','normal']"
            data-frames='[{"from":"y:-50px;sX:2;sY:2;opacity:0;","speed":1000,"to":"o:1;","delay":1500,"ease":"Power4.easeOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]'
            data-startslide="0"
            data-endslide="3"
            data-responsive="on"
            data-responsive_offset="on"
            style="z-index: 9; letter-spacing: -0.5px;">Réalisation de documentaires
          </div>
          <a
            class="tp-caption btn btn-full-rounded btn-l btn-ice"
            data-x="center"
            data-y="middle"
            data-voffset="['100','100','100','100']"
            data-width="['auto','auto','auto','auto']"
            data-textalign="['center','center','center','center']"
            data-frames='[{"from":"y:-50px;sX:2;sY:2;opacity:0;","speed":1000,"to":"o:1;","delay":2000,"ease":"Power4.easeOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]'
            data-startslide="0"
            data-endslide="3"
            data-responsive="on"
            data-responsive_offset="on"
            style="z-index: 9;"
            href="#association">En savoir plus</a>
        </li>
        <li data-transition="fade" data-thumb="<%= image_path("header/header2.jpg") %>"><%= image_tag('header/header2.jpg', class: '', alt: '') %>
          <div
            class="tp-caption font-weight-500 text-uppercase color-white text-center home-header-font"
            data-x="center"
            data-y="middle"
            data-voffset="['-75','-75','-75','-75']"
            data-fontsize="['16','16','16','16']"
            data-lineheight="['26','26','26','26']"
            data-width="['600','600','600','600']"
            data-textalign="['center','center','center','center']"
            data-whitespace="['normal','normal','normal','normal']"
            data-frames='[{"from":"y:-50px;sX:2;sY:2;opacity:0;","speed":1000,"to":"o:1;","delay":1000,"ease":"Power4.easeOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]'
            data-startslide="0"
            data-endslide="3"
            data-responsive="on"
            data-responsive_offset="on"
            style="z-index: 9; letter-spacing: 3px;">Association Oeil de Biche
          </div>
          <div
            class="tp-caption font-weight-700 color-white text-center"
            data-x="center"
            data-y="middle"
            data-voffset="['0','0','0','0']"
            data-fontsize="['55','55','45','35']"
            data-lineheight="['65','65','55','45']"
            data-width="['900','900','700','700']"
            data-textalign="['center','center','center','center']"
            data-whitespace="['normal','normal','normal','normal']"
            data-frames='[{"from":"y:-50px;sX:2;sY:2;opacity:0;","speed":1000,"to":"o:1;","delay":1500,"ease":"Power4.easeOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]'
            data-startslide="0"
            data-endslide="3"
            data-responsive="on"
            data-responsive_offset="on"
            style="z-index: 9; letter-spacing: -0.5px;">Créations originales
          </div>
          <a
            class="tp-caption btn btn-full-rounded btn-l btn-ice"
            data-x="center"
            data-y="middle"
            data-voffset="['100','100','100','100']"
            data-width="['auto','auto','auto','auto']"
            data-textalign="['center','center','center','center']"
            data-frames='[{"from":"y:-50px;sX:2;sY:2;opacity:0;","speed":1000,"to":"o:1;","delay":2000,"ease":"Power4.easeOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]'
            data-startslide="0"
            data-endslide="3"
            data-responsive="on"
            data-responsive_offset="on"
            style="z-index: 9;"
            href="#association">En savoir plus</a>
        </li>
        <li data-transition="fade" data-thumb="<%= image_path("header/header3.jpg") %>"><%= image_tag('header/header3.jpg', class: '', alt: '') %>
          <div
            class="tp-caption font-weight-500 text-uppercase color-white text-center home-header-font"
            data-x="center"
            data-y="middle"
            data-voffset="['-75','-75','-75','-75']"
            data-fontsize="['16','16','16','16']"
            data-lineheight="['26','26','26','26']"
            data-width="['600','600','600','600']"
            data-textalign="['center','center','center','center']"
            data-whitespace="['normal','normal','normal','normal']"
            data-frames='[{"from":"y:-50px;sX:2;sY:2;opacity:0;","speed":1000,"to":"o:1;","delay":1000,"ease":"Power4.easeOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]'
            data-startslide="0"
            data-endslide="3"
            data-responsive="on"
            data-responsive_offset="on"
            style="z-index: 9; letter-spacing: 3px;">Association Oeil de Biche
          </div>
          <div
            class="tp-caption font-weight-700 color-white text-center"
            data-x="center"
            data-y="middle"
            data-voffset="['0','0','0','0']"
            data-fontsize="['55','55','45','35']"
            data-lineheight="['65','65','55','45']"
            data-width="['900','900','700','700']"
            data-textalign="['center','center','center','center']"
            data-whitespace="['normal','normal','normal','normal']"
            data-frames='[{"from":"y:-50px;sX:2;sY:2;opacity:0;","speed":1000,"to":"o:1;","delay":1500,"ease":"Power4.easeOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]'
            data-startslide="0"
            data-endslide="3"
            data-responsive="on"
            data-responsive_offset="on"
            style="z-index: 9; letter-spacing: -0.5px;">Mise en valeur des espaces naturels
          </div>
          <a
            class="tp-caption btn btn-full-rounded btn-l btn-ice"
            data-x="center"
            data-y="middle"
            data-voffset="['100','100','100','100']"
            data-width="['auto','auto','auto','auto']"
            data-textalign="['center','center','center','center']"
            data-frames='[{"from":"y:-50px;sX:2;sY:2;opacity:0;","speed":1000,"to":"o:1;","delay":2000,"ease":"Power4.easeOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]'
            data-startslide="0"
            data-endslide="3"
            data-responsive="on"
            data-responsive_offset="on"
            style="z-index: 9;"
            href="#association">En savoir plus</a>
        </li>
      </ul>
      <div class="tp-bannertimer tp-bottom"></div>
    </div>
    <!-- /.rev_slider -->
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="content-wrapper">
  <nav class="navbar nav-wrapper-dark inverse-text navbar-expand-lg center justify-content-between">
    <div class="container">
      <div class="navbar-header">
        <div class="navbar-brand d-lg-none d-xl-none"><%= link_to root_path do %><%= image_tag('logos/logo1.png', class: '', alt: '') %>
          <% end %>
        </div>
        <div class="navbar-hamburger ml-auto d-lg-none d-xl-none">
          <button class="hamburger animate" data-toggle="collapse" data-target=".navbar-collapse">
            <span></span></button>
        </div>
      </div>
      <!-- /.navbar-header -->
      <div class="collapse navbar-collapse">
        <div class="navbar-nav-wrapper">
          <ul class="nav navbar-nav">
            <li class="nav-item dropdown"><%= link_to 'L\'Association', root_path, class: 'nav-link dropdown-toggle bold-text' %>
              <ul class="dropdown-menu dropdown-menu-left border-top-line">
                <li class="nav-item"><%= link_to 'Qui sommes-nous ?', root_path(@root, anchor: 'association'), class: 'dropdown-item text-color hover-color' %></li>
                <li class="nav-item"><%= link_to 'Nos missions', root_path(@root, anchor: 'mission'), class: 'dropdown-item text-color hover-color' %></li>
                <li class="nav-item"><%= link_to 'Notre équipe', root_path(@root, anchor: 'team'), class: 'dropdown-item text-color hover-color' %></li>
                <li class="nav-item"><%= link_to 'Nos principales réalisations', root_path(@root, anchor: 'realisation'), class: 'dropdown-item text-color hover-color' %></li>
                <li class="nav-item"><%= link_to 'Notre matériel', root_path(@root, anchor: 'equipment'), class: 'dropdown-item text-color hover-color' %></li>
              </ul>
            </li>
            <li class="nav-item"><%= link_to 'Réalisations', projects_path, class: 'nav-link bold-text' %></li>
          </ul>
        </div>
        <div class="navbar-brand d-none d-lg-block"><%= link_to root_path do %><%= image_tag('logos/logo1.png', class: '', alt: '') %>
          <% end %>
        </div>
        <div class="navbar-nav-wrapper">
          <ul class="nav navbar-nav ml-auto">
            <li class="nav-item"><%= link_to 'Actualités', events_path, class: 'nav-link bold-text' %></li>
            <li class="nav-item"><%= link_to 'Blog', articles_path, class: 'nav-link bold-text' %></li>
            <li class="nav-item"><%= link_to 'Contact', new_contact_path, class: 'nav-link bold-text' %></li>
            <% if admin_signed_in? %>
              <li class="nav-item"><%= link_to 'Espace Admin', dashboard_admin_path(current_admin), class: 'nav-link bg-ice dashboard-btn dashboard-text bold-text' %></li>
            <% end %>
          </ul>
        </div>
        <!-- /.navbar-nav-wrapper -->
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OeilDeBiche</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,600,600i,700,700i&display=swap" rel="stylesheet">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="//db.onlinewebfonts.com/c/0e979bd4a3c1c6ac788ed57ac569667f?family=revicons" rel="stylesheet" type="text/css"/>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= render 'layouts/flash' %>
<div id="contenu">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
<a id="scrollUp" href="#top" title="Haut de page" style="position: fixed; z-index: 1001;">
          <span class="btn btn-full-rounded btn-ice btn-icon">
            <i class="fa fa-chevron-up"></i></span></a>
</body>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>